// Comprehensive rule-based subject classifier with 100 keywords per subject
const keywordMap = [
  {
    subject: "Physics",
    keywords: [
      "newton",
      "gravity",
      "force",
      "acceleration",
      "velocity",
      "energy",
      "law of motion",
      "mass",
      "weight",
      "momentum",
      "kinetic",
      "potential",
      "thermal",
      "nuclear",
      "electromagnetic",
      "wave",
      "frequency",
      "amplitude",
      "wavelength",
      "sound",
      "light",
      "optics",
      "reflection",
      "refraction",
      "diffraction",
      "interference",
      "resonance",
      "oscillation",
      "pendulum",
      "spring",
      "friction",
      "tension",
      "pressure",
      "density",
      "buoyancy",
      "fluid",
      "viscosity",
      "turbulence",
      "electricity",
      "current",
      "voltage",
      "resistance",
      "circuit",
      "capacitor",
      "inductor",
      "magnetic",
      "field",
      "flux",
      "induction",
      "transformer",
      "generator",
      "motor",
      "semiconductor",
      "transistor",
      "quantum",
      "photon",
      "electron",
      "proton",
      "neutron",
      "atom",
      "molecule",
      "particle",
      "relativity",
      "einstein",
      "spacetime",
      "blackhole",
      "wormhole",
      "singularity",
      "cosmos",
      "universe",
      "galaxy",
      "nebula",
      "supernova",
      "pulsar",
      "quasar",
      "dark matter",
      "dark energy",
      "expansion",
      "big bang",
      "cosmic",
      "stellar",
      "planetary",
      "orbital",
      "satellite",
      "rocket",
      "thrust",
      "propulsion",
      "aerodynamics",
      "lift",
      "drag",
      "turbine",
      "engine",
      "combustion",
      "thermodynamics",
      "entropy",
      "carnot",
      "efficiency",
      "work",
      "power",
      "torque",
      "angular",
      "centripetal",
      "centrifugal",
      "inertia",
      "moment",
      "equilibrium",
      "stability",
      "harmonic",
      "resonant",
      "damping",
    ],
  },
  {
    subject: "Biology",
    keywords: [
      "photosynthesis",
      "cell",
      "mitochondria",
      "chlorophyll",
      "organism",
      "evolution",
      "dna",
      "gene",
      "protein",
      "enzyme",
      "hormone",
      "antibody",
      "antigen",
      "vaccine",
      "pathogen",
      "bacteria",
      "virus",
      "fungus",
      "parasite",
      "host",
      "symbiosis",
      "mutualism",
      "commensalism",
      "parasitism",
      "ecosystem",
      "biome",
      "habitat",
      "niche",
      "population",
      "community",
      "species",
      "genus",
      "family",
      "order",
      "class",
      "phylum",
      "kingdom",
      "domain",
      "taxonomy",
      "phylogeny",
      "cladogram",
      "fossil",
      "extinction",
      "adaptation",
      "natural selection",
      "survival",
      "fitness",
      "mutation",
      "variation",
      "heritability",
      "genotype",
      "phenotype",
      "allele",
      "dominant",
      "recessive",
      "homozygous",
      "heterozygous",
      "punnett",
      "cross",
      "inheritance",
      "chromosome",
      "meiosis",
      "mitosis",
      "cytokinesis",
      "interphase",
      "prophase",
      "metaphase",
      "anaphase",
      "telophase",
      "centromere",
      "telomere",
      "replication",
      "transcription",
      "translation",
      "mrna",
      "trna",
      "rrna",
      "codon",
      "anticodon",
      "amino acid",
      "peptide",
      "polypeptide",
      "nucleotide",
      "base pair",
      "double helix",
      "complementary",
      "template",
      "polymerase",
      "ligase",
      "restriction",
      "plasmid",
      "vector",
      "transformation",
      "cloning",
      "pcr",
      "gel electrophoresis",
      "sequencing",
      "genomics",
      "proteomics",
      "metabolomics",
      "bioinformatics",
      "biotechnology",
      "genetic engineering",
    ],
  },
  {
    subject: "Chemistry",
    keywords: [
      "atom",
      "molecule",
      "reaction",
      "compound",
      "element",
      "acid",
      "base",
      "periodic table",
      "proton",
      "neutron",
      "electron",
      "nucleus",
      "shell",
      "orbital",
      "valence",
      "ionization",
      "electronegativity",
      "covalent",
      "ionic",
      "metallic",
      "hydrogen bond",
      "van der waals",
      "dipole",
      "polar",
      "nonpolar",
      "solubility",
      "concentration",
      "molarity",
      "molality",
      "normality",
      "ppm",
      "ppb",
      "ph",
      "pka",
      "buffer",
      "indicator",
      "titration",
      "endpoint",
      "equivalence",
      "stoichiometry",
      "limiting reagent",
      "excess",
      "yield",
      "theoretical",
      "actual",
      "percent",
      "empirical",
      "molecular",
      "formula",
      "equation",
      "coefficient",
      "subscript",
      "balanced",
      "unbalanced",
      "reactant",
      "product",
      "catalyst",
      "inhibitor",
      "activation energy",
      "transition state",
      "intermediate",
      "mechanism",
      "rate law",
      "order",
      "half-life",
      "equilibrium",
      "constant",
      "le chatelier",
      "shift",
      "endothermic",
      "exothermic",
      "enthalpy",
      "entropy",
      "gibbs",
      "spontaneous",
      "nonspontaneous",
      "oxidation",
      "reduction",
      "redox",
      "oxidizing agent",
      "reducing agent",
      "electrochemistry",
      "galvanic",
      "electrolytic",
      "anode",
      "cathode",
      "salt bridge",
      "cell potential",
      "nernst",
      "faraday",
      "coulomb",
      "ampere",
      "volt",
      "ohm",
      "conductivity",
      "resistance",
    ],
  },
  {
    subject: "Mathematics",
    keywords: [
      "algebra",
      "calculus",
      "equation",
      "integral",
      "derivative",
      "theorem",
      "geometry",
      "matrix",
      "function",
      "variable",
      "constant",
      "coefficient",
      "polynomial",
      "quadratic",
      "cubic",
      "linear",
      "exponential",
      "logarithm",
      "trigonometry",
      "sine",
      "cosine",
      "tangent",
      "cotangent",
      "secant",
      "cosecant",
      "angle",
      "degree",
      "radian",
      "arc",
      "chord",
      "radius",
      "diameter",
      "circumference",
      "area",
      "perimeter",
      "volume",
      "surface area",
      "triangle",
      "rectangle",
      "square",
      "circle",
      "ellipse",
      "parabola",
      "hyperbola",
      "conic",
      "vertex",
      "focus",
      "directrix",
      "asymptote",
      "limit",
      "continuity",
      "differentiability",
      "critical point",
      "inflection point",
      "maximum",
      "minimum",
      "extrema",
      "optimization",
      "related rates",
      "implicit differentiation",
      "chain rule",
      "product rule",
      "quotient rule",
      "power rule",
      "sum rule",
      "antiderivative",
      "definite integral",
      "indefinite integral",
      "substitution",
      "integration by parts",
      "partial fractions",
      "trigonometric substitution",
      "improper integral",
      "series",
      "sequence",
      "convergence",
      "divergence",
      "geometric",
      "arithmetic",
      "harmonic",
      "taylor",
      "maclaurin",
      "power series",
      "radius of convergence",
      "interval of convergence",
      "absolute convergence",
      "conditional convergence",
      "ratio test",
      "root test",
      "comparison test",
      "limit comparison test",
      "integral test",
      "alternating series test",
      "divergence test",
      "p-series",
      "harmonic series",
      "geometric series",
    ],
  },
  {
    subject: "History",
    keywords: [
      "revolution",
      "empire",
      "war",
      "treaty",
      "ancient",
      "medieval",
      "modern history",
      "dynasty",
      "civilization",
      "culture",
      "society",
      "government",
      "politics",
      "democracy",
      "monarchy",
      "dictatorship",
      "republic",
      "oligarchy",
      "theocracy",
      "feudalism",
      "capitalism",
      "socialism",
      "communism",
      "fascism",
      "nationalism",
      "imperialism",
      "colonialism",
      "independence",
      "liberation",
      "movement",
      "protest",
      "rebellion",
      "uprising",
      "insurrection",
      "coup",
      "assassination",
      "assassination",
      "conspiracy",
      "plot",
      "intrigue",
      "diplomacy",
      "alliance",
      "coalition",
      "confederation",
      "federation",
      "union",
      "secession",
      "annexation",
      "conquest",
      "invasion",
      "occupation",
      "liberation",
      "surrender",
      "victory",
      "defeat",
      "battle",
      "campaign",
      "siege",
      "blockade",
      "embargo",
      "sanction",
      "boycott",
      "strike",
      "riot",
      "massacre",
      "genocide",
      "holocaust",
      "pogrom",
      "persecution",
      "discrimination",
      "segregation",
      "apartheid",
      "civil rights",
      "human rights",
      "suffrage",
      "emancipation",
      "abolition",
      "slavery",
      "serfdom",
      "peasantry",
      "nobility",
      "aristocracy",
      "bourgeoisie",
      "proletariat",
      "middle class",
      "working class",
      "elite",
      "commoner",
      "merchant",
      "artisan",
      "craftsman",
      "guild",
      "trade",
      "commerce",
      "economy",
      "market",
    ],
  },
  {
    subject: "Geography",
    keywords: [
      "continent",
      "ocean",
      "mountain",
      "river",
      "climate",
      "latitude",
      "longitude",
      "map",
      "landform",
      "plateau",
      "valley",
      "canyon",
      "gorge",
      "delta",
      "estuary",
      "fjord",
      "archipelago",
      "peninsula",
      "isthmus",
      "strait",
      "channel",
      "bay",
      "gulf",
      "sea",
      "lake",
      "pond",
      "stream",
      "creek",
      "brook",
      "tributary",
      "watershed",
      "drainage",
      "basin",
      "catchment",
      "floodplain",
      "wetland",
      "marsh",
      "swamp",
      "bog",
      "fen",
      "desert",
      "savanna",
      "grassland",
      "prairie",
      "steppe",
      "tundra",
      "taiga",
      "forest",
      "rainforest",
      "jungle",
      "woodland",
      "shrubland",
      "heath",
      "moor",
      "mangrove",
      "coral reef",
      "atoll",
      "island",
      "volcanic",
      "seismic",
      "tectonic",
      "plate",
      "fault",
      "earthquake",
      "tsunami",
      "volcano",
      "eruption",
      "lava",
      "magma",
      "crater",
      "caldera",
      "geyser",
      "hot spring",
      "mineral",
      "ore",
      "deposit",
      "vein",
      "lode",
      "quarry",
      "mine",
      "extraction",
      "refinement",
      "processing",
      "manufacturing",
      "industrial",
      "agricultural",
      "urban",
      "rural",
    ],
  },
  {
    subject: "Computer Science",
    keywords: [
      "algorithm",
      "programming",
      "code",
      "software",
      "hardware",
      "database",
      "network",
      "internet",
      "computer",
      "laptop",
      "desktop",
      "server",
      "cloud",
      "virtual",
      "digital",
      "binary",
      "data",
      "information",
      "bit",
      "byte",
      "kilobyte",
      "megabyte",
      "gigabyte",
      "terabyte",
      "petabyte",
      "exabyte",
      "zettabyte",
      "yottabyte",
      "file",
      "folder",
      "directory",
      "path",
      "url",
      "http",
      "https",
      "ftp",
      "smtp",
      "pop",
      "imap",
      "dns",
      "ip",
      "tcp",
      "udp",
      "router",
      "switch",
      "hub",
      "modem",
      "firewall",
      "virus",
      "malware",
      "spyware",
      "adware",
      "trojan",
      "worm",
      "phishing",
      "encryption",
      "decryption",
      "password",
      "authentication",
      "authorization",
      "login",
      "logout",
      "session",
      "cookie",
      "cache",
      "buffer",
      "memory",
      "ram",
      "rom",
      "cpu",
      "gpu",
      "motherboard",
      "processor",
      "core",
      "thread",
      "multitasking",
      "multiprocessing",
      "parallel",
      "serial",
      "asynchronous",
      "synchronous",
      "real-time",
      "batch",
      "interactive",
      "command",
      "interface",
      "gui",
      "cli",
    ],
  },
  {
    subject: "Literature",
    keywords: [
      "novel",
      "poem",
      "drama",
      "play",
      "story",
      "tale",
      "fable",
      "myth",
      "legend",
      "folklore",
      "epic",
      "ballad",
      "sonnet",
      "haiku",
      "limerick",
      "ode",
      "elegy",
      "pastoral",
      "satire",
      "parody",
      "allegory",
      "metaphor",
      "simile",
      "symbol",
      "imagery",
      "alliteration",
      "assonance",
      "consonance",
      "rhyme",
      "rhythm",
      "meter",
      "verse",
      "stanza",
      "couplet",
      "quatrain",
      "octave",
      "sestet",
      "refrain",
      "chorus",
      "canto",
      "chapter",
      "scene",
      "act",
      "prologue",
      "epilogue",
      "monologue",
      "dialogue",
      "soliloquy",
      "aside",
      "stage direction",
      "character",
      "protagonist",
      "antagonist",
      "hero",
      "villain",
      "antihero",
      "foil",
      "stock character",
      "round character",
      "flat character",
      "dynamic",
      "static",
      "development",
      "arc",
      "plot",
      "exposition",
      "rising action",
      "climax",
      "falling action",
      "resolution",
      "denouement",
      "conflict",
      "theme",
      "motif",
      "symbolism",
      "irony",
      "foreshadowing",
      "flashback",
      "stream of consciousness",
      "point of view",
    ],
  },
  {
    subject: "Economics",
    keywords: [
      "market",
      "supply",
      "demand",
      "price",
      "cost",
      "profit",
      "revenue",
      "income",
      "expense",
      "budget",
      "investment",
      "savings",
      "debt",
      "credit",
      "interest",
      "loan",
      "mortgage",
      "insurance",
      "tax",
      "tariff",
      "subsidy",
      "inflation",
      "deflation",
      "recession",
      "depression",
      "boom",
      "bust",
      "cycle",
      "trend",
      "growth",
      "decline",
      "stagnation",
      "unemployment",
      "employment",
      "labor",
      "wage",
      "salary",
      "bonus",
      "commission",
      "overtime",
      "union",
      "strike",
      "collective bargaining",
      "minimum wage",
      "living wage",
      "poverty",
      "wealth",
      "inequality",
      "gdp",
      "gnp",
      "gni",
      "per capita",
      "nominal",
      "real",
      "adjusted",
      "index",
      "consumer",
      "producer",
      "wholesale",
      "retail",
      "import",
      "export",
      "trade",
      "balance",
      "surplus",
      "deficit",
      "exchange rate",
      "currency",
      "dollar",
      "euro",
      "yen",
      "pound",
      "central bank",
      "federal reserve",
      "monetary policy",
      "fiscal policy",
      "stimulus",
      "austerity",
      "quantitative easing",
      "bailout",
    ],
  },
  {
    subject: "Psychology",
    keywords: [
      "mind",
      "brain",
      "consciousness",
      "unconscious",
      "subconscious",
      "memory",
      "learning",
      "cognition",
      "perception",
      "sensation",
      "attention",
      "focus",
      "concentration",
      "awareness",
      "alertness",
      "vigilance",
      "emotion",
      "feeling",
      "mood",
      "affect",
      "happiness",
      "sadness",
      "anger",
      "fear",
      "anxiety",
      "depression",
      "stress",
      "trauma",
      "ptsd",
      "phobia",
      "panic",
      "obsession",
      "compulsion",
      "addiction",
      "dependence",
      "withdrawal",
      "tolerance",
      "sensitivity",
      "resistance",
      "immunity",
      "personality",
      "character",
      "temperament",
      "disposition",
      "attitude",
      "belief",
      "value",
      "norm",
      "social",
      "group",
      "crowd",
      "mob",
      "team",
      "organization",
      "institution",
      "culture",
      "society",
      "community",
      "family",
      "peer",
      "friend",
      "colleague",
      "acquaintance",
      "stranger",
      "relationship",
      "attachment",
      "bond",
      "trust",
      "loyalty",
      "betrayal",
      "conflict",
      "resolution",
      "communication",
      "language",
      "speech",
      "gesture",
      "expression",
      "body language",
      "nonverbal",
      "verbal",
    ],
  },
];

function inferSubject(text,next) {
  try {
    const lowerText = text.toLowerCase();
    for (const entry of keywordMap) {
      for (const keyword of entry.keywords) {
      if (lowerText.includes(keyword)) {
        return entry.subject;
      }
      }
    }
    return "General";
  } catch (error) {
   next(error)
  }
}

module.exports = { inferSubject };
